### ISSUE TITLE
Wrong numbering of subsections

### ISSUE THREAD

**Issue by fedormyskin** [GroningenDH/Cultural-Analytics-Open-Science-Guide#1]
@PaschalisAg 

The numbering of the subsections is wrong starting from chapter 3.
It should be:
3 README file
3.1 What is a README file and how to write a good one?
3.2 Conventions to write a good README file

Even the following sections have numbering not corresponding to the section number.

**Comment by PaschalisAg** [comment]
@fedormyskin I just fixed the links to download the datasets and the structure of the individual pages. If there is anything else to do we can close this issue (https://groningendh.github.io/Cultural-Analytics-Open-Science-Guide/).
